In [1]:
import numpy as np

In [2]:
arr1 = np.arange(20,25)
arr1

array([20, 21, 22, 23, 24])

In [3]:
print(arr1)

[20 21 22 23 24]


In [7]:
arr1 = np.arange(2000)
arr1

array([   0,    1,    2, ..., 1997, 1998, 1999])

In [9]:
import sys
np.set_printoptions(threshold = sys.maxsize)

9223372036854775807

In [13]:
# arr1 = np.arange(20000).reshape(500,40)
# arr1

# Reshaping an array

In [23]:
arr1 = np.arange(1000).reshape(100,10)
# arr1



In [32]:
arr1 = np.arange(1000).reshape(-50,10)
# arr1

In [33]:
ind_state = np.array(['AP', 'MP','UP', 'KA', 'TN','KL', 'RJ', 'JK', 'HP', 'DL', 'WB', 'MH'])
ind_state

array(['AP', 'MP', 'UP', 'KA', 'TN', 'KL', 'RJ', 'JK', 'HP', 'DL', 'WB',
       'MH'], dtype='<U2')

In [38]:
ind_state.reshape(4,-1)

array([['AP', 'MP', 'UP'],
       ['KA', 'TN', 'KL'],
       ['RJ', 'JK', 'HP'],
       ['DL', 'WB', 'MH']], dtype='<U2')

In [39]:
# Transpose of a matrix - rows to coluns and columns to rows
ind_state.reshape(4,-1).T

array([['AP', 'KA', 'RJ', 'DL'],
       ['MP', 'TN', 'JK', 'WB'],
       ['UP', 'KL', 'HP', 'MH']], dtype='<U2')

In [41]:
np.reshape(ind_state, (4,-1), order = 'C')   # Row major format

array([['AP', 'MP', 'UP'],
       ['KA', 'TN', 'KL'],
       ['RJ', 'JK', 'HP'],
       ['DL', 'WB', 'MH']], dtype='<U2')

In [45]:
np.reshape(ind_state, (4,-1), order = '')   #Column major format

array([['AP', 'MP', 'UP'],
       ['KA', 'TN', 'KL'],
       ['RJ', 'JK', 'HP'],
       ['DL', 'WB', 'MH']], dtype='<U2')

# Basic operation on an array

In [49]:
# lst1 = [10,20,30]
# lst2 = [40,50,60]
# print(lst1+2)

In [67]:
arr1 = np.array([10,20,30,40,50])

# Adding a scalar quantity into an array
arr1 + 2

# Multiplying a scalar quantity into an array
arr1 * 2

# Subtracting a scalar quantity into an array
arr1 - 2

# Dividing an array with a scalar quantity
arr1 / 2
arr1 // 2

# raising every element to the power 2
arr1 ** 2

# Performing modulo operation on every element of an array
arr1 % 3

# Comparison operation - returns the masked array
arr1 < 30
arr1 > 30

# Finding the square root pf all elements
np.sqrt(arr1)

# FInding the log of all elements
np.log(arr1)

# finding the sine of all elemnets, cos, tan, arcsin, arccos, arctan
np.sin(arr1 *np.pi/180)


array([0.17364818, 0.34202014, 0.5       , 0.64278761, 0.76604444])

In [2]:
# Dot prodct of matrix
arr1 = np.array([10,11,12,13]).reshape(2,2)
arr1

array([[10, 11],
       [12, 13]])

In [5]:
arr2 = np.array([20,21,22,23]).reshape(2,2)
arr2

array([[20, 21],
       [22, 23]])

In [71]:

arr1 * arr2

array([[200, 231],
       [264, 299]])

In [76]:
# Dot product
# [[(10*20+11*22), (10*21+11*23)],
# [(12*20+13*22), (12*21+13*23)]]
# [[442, 463], [513, 551]]

# np.dot(arr1, arr2)
# arr1.dot(arr2)

array([[442, 463],
       [526, 551]])

In [3]:
arr1


array([[10, 11],
       [12, 13]])

In [6]:
arr2

array([[20, 21],
       [22, 23]])

In [80]:
# arr1 = arr1 * arr2
# arr1

array([[200, 231],
       [264, 299]])

In [83]:
# arr1 += arr2
# arr1

In [13]:
# Unary operations - Aggregate function - sum, min,max

# np.sum(arr1)
# np.max(arr1)
# np.min(arr1)

# arr1.sum()
# arr1.max()
# arr1.min()

10

In [15]:
arr3 = np.arange(25,50).reshape(5,-1)
arr3

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [18]:
# Finding the sum of all elements along th erows
np.sum(arr3, axis = 1)
np.sum(arr3, axis = 0)

array([175, 180, 185, 190, 195])

In [20]:
# Finding the max of all elements along the rows
np.max(arr3, axis = 1)
np.max(arr3, axis = 0)

array([45, 46, 47, 48, 49])

In [22]:
# Finding the min of all elements along the rows
np.min(arr3, axis = 1)
np.min(arr3, axis = 0)

array([25, 26, 27, 28, 29])

In [23]:
arr3

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [24]:
arr4 = np.array([1,2,3,4,5])
arr3+arr4

array([[26, 28, 30, 32, 34],
       [31, 33, 35, 37, 39],
       [36, 38, 40, 42, 44],
       [41, 43, 45, 47, 49],
       [46, 48, 50, 52, 54]])

In [26]:
# arr5 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# arr3+arr5

In [ ]:
# Universal Functions

In [27]:
np.add(10,11)

21

In [28]:
np.add(np.array([[10,11],[12,13]]), np.array([[20,21],[22,23]]))

array([[30, 32],
       [34, 36]])

In [29]:
np.multiply(np.array([[10,11],[12,13]]), np.array([[20,21],[22,23]]))

array([[200, 231],
       [264, 299]])

In [30]:
np.dot(np.array([[10,11],[12,13]]), np.array([[20,21],[22,23]]))

array([[442, 463],
       [526, 551]])

In [33]:
# print(dir(np))
np.square(arr3)

array([[ 625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156],
       [1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936],
       [2025, 2116, 2209, 2304, 2401]])

In [36]:
arr1 = np.array([0,30,45,60,90])
# np.sin(arr1*np.pi/180)
radian = np.radians(arr1)
print(np.sin(radian))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [ ]:
# Bitwise function in Numpy - bitwise_and, bitwise_or, bitwise_not, bitwise_xor, binary_repr() = bin()

In [37]:
arr1

array([ 0, 30, 45, 60, 90])

In [43]:
# np.binary_repr(num)

np.binary_repr(10)

'1010'

In [44]:
print(np.bitwise_and(np.array([[10,11],[12,13]]), np.array([[20,21],[22,23]])))

[[0 1]
 [4 5]]


In [49]:
print(np.bitwise_or(np.array([[10,11],[12,13]]), np.array([[20,21],[22,23]])))

[[30 31]
 [30 31]]


In [50]:
print(np.bitwise_xor(np.array([[10,11],[12,13]]), np.array([[20,21],[22,23]])))

[[30 30]
 [26 26]]


In [56]:
# Broadcasting 
# 1. at least one array should be of single dimension
# 2. No of elelemnt in single dimension array and no of columns in multi dimension array should be same - row wise broadcasting

# if both the arrays are of 2/3/4... dimensuon
# no Coulmn should be 1 and no of rows should match in both the arrays

a1 = np.arange(30).reshape(6,-1)
print(a1)
a2 = np.array([[10,11,12,13,14],[15,16,17,18,19]])
print(a1+a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


ValueError: operands could not be broadcast together with shapes (6,5) (2,5) 

In [57]:
# Case 1

# [[ 0  1  2  3  4]  [10,11,12,13,14]
#  [ 5  6  7  8  9]  [10,11,12,13,14]
#  [10 11 12 13 14]  [10,11,12,13,14]
#  [15 16 17 18 19]  [10,11,12,13,14]
#  [20 21 22 23 24]  [10,11,12,13,14]
#  [25 26 27 28 29]] [10,11,12,13,14]


# [10,11,12,13,14]



# Case 2
# [[ 0  1  2  3  4]   [10 10 10 10 10]
#  [ 5  6  7  8  9]   [11 11 11 11 11]
#  [10 11 12 13 14]   [12 12 12 12 12]
#  [15 16 17 18 19]   [13 13 13 13 13]
#  [20 21 22 23 24]   [14 14 14 14 14]
#  [25 26 27 28 29]]  [15 15 15 15 15]


# [[10],
#  [11],
#  [12],
#  [13],
#  [14],
#  [15]]

# Case 3
# [[10,11,12,13,14],
[20,21,22,23,24]]

# [[10],
#  [11],
#  [12],
#  [13],
#  [14],
#  [15]]

[10,11,12,13,14] [10 10 10 10 10]
[10,11,12,13,14] [11 11 11 11 11]
[10,11,12,13,14] [12 12 12 12 12]
[10,11,12,13,14] [13 13 13 13 13]
[10,11,12,13,14] [14 14 14 14 14]
[10,11,12,13,14] [15 15 15 15 15]



In [58]:
# Statistical functions
pop_data = np.genfromtxt('data/population_2017.csv', usecols = 1, delimiter = ',', skip_header = 1)
pop_data

array([   792.,   1300.,   1618.,   2910.,   4049.,   5177.,   6320.,
        11192.,  11359.,  11773.,  14909.,  17380.,  21729.,  25398.,
        31196.,  33400.,  34571.,  35446.,  37922.,  38695.,  40120.,
        49290.,  53127.,  55144.,  55345.,  55641.,  56480.,  61349.,
        61559.,  73925.,  76965.,  84287.,  94737., 102012., 104901.,
       105264., 105544., 107825., 108020., 109897., 116398., 160539.,
       164229., 165314., 178844., 196440., 204327., 253045., 276244.])

In [59]:
pop_data.shape

(49,)

In [60]:
print('Mean = ', np.mean(pop_data))
print('Meadian = ', np.median(pop_data))
print('Standard deviation = ', np.std(pop_data))
print('Variance = ', np.var(pop_data))

Mean =  73958.12244897959
Meadian =  55345.0
Standard deviation =  67180.61487091337
Variance =  4513235014.433986


# Indexing and slicing

In [67]:
arr1 = np.arange(25,30)
arr1

array([25, 26, 27, 28, 29])

In [76]:
#Indexing in 1D array

# Array supports +ve and negative indexing both
print(arr1[0])
print(arr1[-1])
print(arr1[3])



# print(len(arr1))

25
29
28
5


In [75]:
# Slicing in 1D array

print(arr1[1:3])
print(arr1[-2:-5:-1])
print(arr1[::2])
print(arr1[::-1])


[26 27]
[28 27 26]
[25 27 29]
[29 28 27 26 25]


# Indexing and slicng in 2D Array

In [77]:
arr2 = np.arange(25,50).reshape(5,5)
arr2

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [78]:
print(arr2.shape)

(5, 5)


In [79]:
# Accessing row at index 2
print(arr2[2])


[35 36 37 38 39]


In [81]:
# Accessing 37 from ar2
print(arr2[2][2])  # Works onlist as well
print(arr2[2,2])   #This is not possible in list

37
37


In [91]:
# Accessing 2nd column
arr2[:, 2:3]

array([[27],
       [32],
       [37],
       [42],
       [47]])

In [92]:
print(arr2[2:4, 2:4])

[[37 38]
 [42 43]]


In [93]:
# array([[25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34],
#        [35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44],
#        [45, 46, 47, 48, 49]])


print(arr2[::2, 2::2])

[[27 29]
 [37 39]
 [47 49]]


In [ ]:
np.array([10,11,12,13]) * [2, 2, 2, 2]

In [ ]:
np.array([[10,11],[12,13]]) + [[2,2],[2,2]]