In [ ]:
Sequence characters in regular expression:-
    1. \d - any digit from 0 to 9
    2. \D - any non-digit -
    3. \s - white space e.g.:- \t,\n,\r,\v,\f
    4. \S - non white space character
    5. \w - any alphanumeric character e.g.:- (A to Z, a to z, 0 to 9)
    6. \W - any non alphanumeric character
    7. \b - represents a space around words
    8. \A - matches only at the start of the string
    9. \Z - matches only at the end of the string

Characters represents more than one character to be matched in the string is called Quantifiers.
    1. + - represents 1 or more repetitions of the preceding regex exp
    2. * - 0 or more repetitions of the preceding regex exp
    3. ? - 0 or 1 repetitions of the preceding regex exp
    4. {m} - exactly m occurences
    5. {m,n} - from m to n. m defaults to 0 n to infinity. Always goes for higher bound i.e n and then m
    
Special Characters in regex:-
    1. \ - Escape special character
    2. . - matches any character except new line
    3. ^ - matches begining of the string
    4. $ - matches ending of a string
    5. [...] - Denotes set of possible charcaters. e.g. [6p-t]matches any characters from 6,p,q,r,s or t.
    6. [^...] - Matches every characters except the ones inside brackets. e.g [^6p-t]matches every characters
    except 6,p,q,r,s or t.
    7. (...) - Matches the regular expression inside the parenthesis and the result can be captured.
    8. R|S - Matches the regex either R or S.

In [20]:
import re
mystr = 'cat mat rat hat bat can cap cp9 cy5'
reg = r'c\w\w$'
print(re.findall(reg, mystr))

['cy5']


In [32]:
import re
my_str = 'peterpiper picked a peck of pickled peppers.'
reg = r'[Pp]\w{3,}r'
print(re.findall(reg, my_str))

['peterpiper', 'pepper']


In [7]:
import re
my_str = 'peter piper picked a peck of pickled peppers.'
reg = r'[Pp]\w{3,}r\b'
print(re.findall(reg, my_str))

['peter', 'piper']


In [28]:
import re
my_str = 'peter piper picked a peck of pickled peppers  pry675tgfd.'
reg = r'[Pp]\w{3,}r'
print(re.findall(reg, my_str))
print(my_str)

['peter', 'piper', 'pepper']
peter piper picked a peck of pickled peppers  pry675tgfd.


In [11]:
import re
my_str = 'peter piper picked a peck of pickled peppers.'
reg = r'[Pp]\w{3,4}'
print(re.findall(reg, my_str))

['peter', 'piper', 'picke', 'peck', 'pickl', 'peppe']


In [ ]:
# \w\w\w = \w{3}

In [29]:
import re
my_str = 'peter piper picked a peck of pickled peppers. p p98 pgf56'
reg = r'[Pp]\w+'
print(re.findall(reg, my_str))

['peter', 'piper', 'picked', 'peck', 'pickled', 'peppers', 'p98', 'pgf56']


In [31]:
import re
my_str = 'peter piper picked a peck of pickled peppers. p p98 pgf56'
reg = r'[Pp]\w?'
print(re.findall(reg, my_str))

['pe', 'pi', 'pe', 'pi', 'pe', 'pi', 'pe', 'pp', 'p', 'p9', 'pg']


In [21]:
import re
# my_str = 'peter piper pic\nked a peck of pick\nled peppers.'
my_str = 'abc pet xyz'
reg = r'(pet)+'
print(re.search(reg, my_str))


my_str1 = 'abc petttt xyz'
reg = r'(pet+)'
print(re.search(reg, my_str1).group())

my_str2 = 'abc petpetpet xyz'
reg = r'(pet)+'
print(re.search(reg, my_str2).group())

<re.Match object; span=(4, 7), match='pet'>
petttt
petpetpet


In [23]:
reg = r'This is Python \nclass'
print(reg)

This is Python \nclass


In [35]:
#Write the regular expression and use proper method which Retrieves all words having 5 characters.
#Output:- ['peter', 'giper']
import re
str = "peter giper picked a peck of pickled peppers"
reg = r'\b\w{5}\b'
print(re.findall(reg,str))

['peter', 'giper']


In [39]:
#Write the regular expression and use proper method which Retrieves all words having at least 4 characters.
#Output:- ['Retrieving', 'wor$ds', 'having', 'least', 'characters']
import re
str = "Retrieving all wor$ds having at least 4 characters"
reg = r'\w{4,}'
print(re.findall(reg,str))

['Retrieving', 'having', 'least', 'characters']


In [41]:
#Write the regular expression and use proper method which Retrieves only digits from the string.
#Output:- ['8', '11']
import re
str = 'The election in delhi will be held on 8 and result for the same will be declared on 11'
reg = r'\d+'
print(re.findall(reg,str))

['8', '11']


In [43]:
#Write the regular expression and use proper method which Retrieves all words starting with a digit.
#Output:- ['8th', '11th']
import re
str = 'The election in delhi will be held on 8th and result for the same will be declared on 11th'
reg = r'\b\d+\w+\b'
print(re.findall(reg,str))


['8th', '11th']


In [71]:
##Write the regular expression and use proper method which Retrieves name starting with 'an' or 'ak'.
#Output:- ['anil', 'akhil', 'anant', 'ankur']
import re
str = 'anil akhil anant abhi arun arati arundhati abhijit ankur '
reg = r'an\w+|ak\w+ '
print(re.findall(reg,str))


['anil', 'akhil ', 'anant', 'ankur']


In [72]:
str = "petergiperpickedapeckofpickledpeppers"
# pe/of/te
reg = r'pe|of|te'
print(re.findall(reg,str))

['pe', 'te', 'pe', 'pe', 'of', 'pe', 'pe']


In [73]:
str = "peter giper picked a peck of pickled peppers"
reg = r'p\w{3,5}'
print(re.findall(reg,str))

['peter', 'picked', 'peck', 'pickle', 'pepper']


In [80]:
str = "petper giper picked a peck of pickled peppers"
reg = r'p\w{3,5}?'
print(re.findall(reg,str))

['petper', 'picked', 'peck', 'pickle', 'pepper']


In [84]:
str = "petper giper picked a peck of pickled peppers"
reg = r'p\w??'
print(re.findall(reg,str))

['p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p']


In [86]:
str = "petper giper picked a peck of pickled peppers"
reg = r'p\w*?'
print(re.findall(reg,str))

['p', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p']


In [85]:
str = "petper giper picked a peck of pickled peppers"
reg = r'p\w+?'
print(re.findall(reg,str))

['pe', 'pe', 'pe', 'pi', 'pe', 'pi', 'pe', 'pp']


# Numpy

In [88]:
# lst = [10,20,30]
# [i*2 for i in lst]
# lst * 2

[10, 20, 30, 10, 20, 30]

In [89]:
# import numpy as np
# arr = np.array([10,20,30])
# arr*2

array([20, 40, 60])

In [90]:
import numpy as np

In [91]:
# Creating an array using list
lst = [10,20,30,40]
lst

[10, 20, 30, 40]

In [92]:
arr1 = np.array(lst)
arr1

array([10, 20, 30, 40])

In [93]:
arr1.dtype

dtype('int64')

In [94]:
arr1.shape

(4,)

In [95]:
arr1.size

4

In [96]:
arr1.ndim

1

In [98]:
# Creating an array using Tuple
tpl = 10,20,30,40
tpl

(10, 20, 30, 40)

In [99]:
arr2 = np.array(tpl)
arr2

array([10, 20, 30, 40])

In [100]:
print(arr2.dtype)
print(arr2.shape)
print(arr2.size)
print(arr2.ndim)

int64
(4,)
4
1


In [105]:
# Creating an array using arange = range
# arange(start, stop, step)
# arange(stop)

arr3 = np.arange(11,21)
arr3


arr3 = np.arange(11,21, 3)
arr3

arr3 = np.arange(21,11, -3)
arr3

arr3 = np.arange(11)
arr3



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
# creating a multidimensional aray using arange function

arr4 = np.arange(11,23).reshape(4,3)
arr4

arr4 = np.arange(11,23).reshape(3,4)
arr4


arr4 = np.arange(11,23).reshape(6,2)
arr4

arr4 = np.arange(11,23).reshape(2,6)
arr4

arr4 = np.arange(11,23).reshape(1,12)
arr4

arr4 = np.arange(11,23).reshape(12,1)
arr4

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22]])

In [109]:
print(arr4.dtype)
print(arr4.shape)
print(arr4.size)
print(arr4.ndim)

int64
(5, 2)
10
2


In [121]:
# Creating a multidimesional array with MD List

lst = [[1,2,3],[4,5,6]]
arr5 = np.array(lst)
arr5

lst = [1,2,3,4,5,6]
arr5 = np.array(lst).reshape(3,2).reshape(2,3)
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
arr6 = np.arange(11,21,0.1).reshape(2,2,25)
arr6

array([[[11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9,
         12. , 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9,
         13. , 13.1, 13.2, 13.3, 13.4],
        [13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3, 14.4,
         14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
         15.5, 15.6, 15.7, 15.8, 15.9]],

       [[16. , 16.1, 16.2, 16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 16.9,
         17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6, 17.7, 17.8, 17.9,
         18. , 18.1, 18.2, 18.3, 18.4],
        [18.5, 18.6, 18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4,
         19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1, 20.2, 20.3, 20.4,
         20.5, 20.6, 20.7, 20.8, 20.9]]])

In [128]:
arr7 = np.linspace(11,21, 100)
arr7

array([11.        , 11.1010101 , 11.2020202 , 11.3030303 , 11.4040404 ,
       11.50505051, 11.60606061, 11.70707071, 11.80808081, 11.90909091,
       12.01010101, 12.11111111, 12.21212121, 12.31313131, 12.41414141,
       12.51515152, 12.61616162, 12.71717172, 12.81818182, 12.91919192,
       13.02020202, 13.12121212, 13.22222222, 13.32323232, 13.42424242,
       13.52525253, 13.62626263, 13.72727273, 13.82828283, 13.92929293,
       14.03030303, 14.13131313, 14.23232323, 14.33333333, 14.43434343,
       14.53535354, 14.63636364, 14.73737374, 14.83838384, 14.93939394,
       15.04040404, 15.14141414, 15.24242424, 15.34343434, 15.44444444,
       15.54545455, 15.64646465, 15.74747475, 15.84848485, 15.94949495,
       16.05050505, 16.15151515, 16.25252525, 16.35353535, 16.45454545,
       16.55555556, 16.65656566, 16.75757576, 16.85858586, 16.95959596,
       17.06060606, 17.16161616, 17.26262626, 17.36363636, 17.46464646,
       17.56565657, 17.66666667, 17.76767677, 17.86868687, 17.96

In [129]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [133]:
np.ones((4,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [134]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
np.empty((4,5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [2.68156159e+154, 2.68156159e+154, 8.39911598e-323,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [140]:
np.random.rand(3,4)

array([[0.50435766, 0.66737713, 0.75622668, 0.02761093],
       [0.33619013, 0.12410195, 0.51303622, 0.50576402],
       [0.40982131, 0.08461071, 0.11473353, 0.45538961]])