In [3]:
import numpy as np

In [5]:
arr1 = np.arange(25,30)
arr1

array([25, 26, 27, 28, 29])

In [6]:
x = arr1[0],arr1[-1],arr1[2]
print(x)

(25, 29, 27)


In [8]:
r = np.array([2,3,0,-1])

In [9]:
arr1[r]

array([27, 28, 25, 29])

In [10]:
# Accessing the elements in an array using array of indices

arr2 = np.arange(25,50).reshape(5,5)
arr2


array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [11]:
arr2[r]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29],
       [45, 46, 47, 48, 49]])

In [13]:
c = np.array([-1, 1, 2,0])

In [14]:
arr2[r,c]

array([39, 41, 27, 45])

In [15]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [17]:
k = np.array([[1,2],[0,1]])

In [18]:
fruit[k]

array([[['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
        ['Apricot', 'Apple', 'Blue berry', 'Black berry']],

       [['Banana', 'Mango', 'Guava', 'Avacado'],
        ['Papaya', 'Jack fruit', 'Plum', 'Strawberry']]], dtype='<U11')

In [20]:
v = np.array([[3,3], [2,1]])

In [21]:
fruit[k,v]

array([['Strawberry', 'Black berry'],
       ['Guava', 'Jack fruit']], dtype='<U11')

In [22]:
fruit[k,v] = 'Chillies'
fruit

array([['Banana', 'Mango', 'Chillies', 'Avacado'],
       ['Papaya', 'Chillies', 'Plum', 'Chillies'],
       ['Apricot', 'Apple', 'Blue berry', 'Chillies']], dtype='<U11')

In [23]:
# Indexing using boolean array

arr2 = np.arange(25,50).reshape(5,5)
arr2


array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [29]:
bool_arr = arr2>37
bool_arr

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [26]:
arr2[bool_arr]

array([38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
arr2[arr2>37]

array([38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [33]:
np.sum(arr2<37)

12

In [34]:
np.sum(arr2[arr2<37])

366

In [35]:
np.count_nonzero(arr2<37)

12

In [37]:
np.sum(arr2<37, axis = 1)
np.sum(arr2<37, axis = 0)

array([3, 3, 2, 2, 2])

In [39]:
np.any(arr2>50)

False

In [41]:
np.all(arr2>50)

False

# Structured Array

In [67]:
emp_name = ['Ross', 'Andy', 'Joe', 'Ramesh']
emp_id = [101, 102, 103, 104]
emp_sal = [10000.00, 18000.00, 20000.00,np.nan]

In [64]:
emp_data = np.zeros(4, dtype = {'names':('name', 'id', 'sal'), 'formats': ('U10', 'i4', 'f8')})
emp_data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('id', '<i4'), ('sal', '<f8')])

In [62]:
emp_data.dtype

dtype([('name', '<U10'), ('id', '<i4'), ('sal', '<f8')])

In [68]:
emp_data['name'] = emp_name
emp_data['id'] = emp_id
emp_data['sal'] = emp_sal
emp_data

array([('Ross', 101, 10000.), ('Andy', 102, 18000.), ('Joe', 103, 20000.),
       ('Ramesh', 104,    nan)],
      dtype=[('name', '<U10'), ('id', '<i4'), ('sal', '<f8')])

In [58]:
emp_data['name']

array(['Ross', 'Andy', 'Joe', 'Ramesh'], dtype='<U10')

In [59]:
emp_data['id']

array([101, 102, 103, 104], dtype=int32)

In [60]:
emp_data['sal']

array([10000., 18000., 20000., 15000.])

In [61]:
emp_data[-1]['name']

'Ramesh'

# Array Broadcasting

In [69]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [71]:
a = 10


In [72]:
arr1 + a

array([10, 11, 12, 13, 14])

In [79]:
arr2 = np.arange(10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
arr2+a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [75]:
arr3 = np.arange(25).reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
arr1.shape


(5,)

In [77]:
arr3.shape

(5, 5)

In [78]:
arr3 + arr1

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23],
       [20, 22, 24, 26, 28]])

In [80]:
arr3+arr2

ValueError: operands could not be broadcast together with shapes (5,5) (2,5) 

In [81]:
# Column wise Broadcasting
arr3



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
arr4 = arr1.reshape(5,1)

In [84]:
arr3 * arr1.reshape(5,1)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28],
       [45, 48, 51, 54, 57],
       [80, 84, 88, 92, 96]])

In [87]:
# Broadcasting along rows and columns

arr4


array([[0],
       [1],
       [2],
       [3],
       [4]])

In [88]:
arr1

array([0, 1, 2, 3, 4])

In [89]:
arr4 * arr1

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

# Iterating over an array

In [90]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [91]:
for ele in arr1:
    print(ele)

0
1
2
3
4


In [92]:
arr3 = np.arange(25).reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [94]:
for i in arr3:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [95]:
for i in arr3.flatten():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [96]:
arr3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [97]:
for i in np.nditer(arr3, order ='C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [98]:
for i in np.nditer(arr3, order ='F'):
    print(i)

0
5
10
15
20
1
6
11
16
21
2
7
12
17
22
3
8
13
18
23
4
9
14
19
24


# Splitting an array

In [113]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [104]:
# Splitting arr1 into 5 equal size
np.split(arr1,5)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24])]

In [105]:
# Splitting an array at specified position
np.split(arr1, [3, 9, 17, 21])

[array([0, 1, 2]),
 array([3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20]),
 array([21, 22, 23, 24])]

In [114]:
arr2 = arr1.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [121]:
# Horizontal split

h1,h2, h3 = np.split(arr2, [2, 3], axis = 1)
h1

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [122]:
h2

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [123]:
h3

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [118]:
np.hsplit(arr2, [2,])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]), array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19],
        [22, 23, 24]])]

In [119]:
np.split(arr2, [2, 3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [120]:
np.vsplit(arr2, [2, 3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

# Views & Copy

In [124]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [140]:
v1 = arr1[2:3]
v1

array([555])

In [141]:
arr1[2] = 222

In [142]:
arr1

array([  0,   1, 222,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [143]:
v1[0] = 333

In [144]:
v1

array([333])

In [145]:
arr1

array([  0,   1, 333,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [133]:
v2 = arr1[2:5]
v2

array([222,   3,   4])

In [134]:
arr1[2] = 444

In [135]:
arr1

array([  0,   1, 444,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [136]:
v2

array([444,   3,   4])

In [137]:
v2[0] = 555
v2

array([555,   3,   4])

In [138]:
arr1

array([  0,   1, 555,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [146]:
v3 = arr1.view()
v3

array([  0,   1, 333,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

# copy()

In [147]:
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [148]:
a = arr2
a

array([0, 1, 2, 3, 4])

In [149]:
c = np.copy(a)
c

array([0, 1, 2, 3, 4])

In [150]:
arr2[0] = 111

In [151]:
arr2

array([111,   1,   2,   3,   4])

In [152]:
a

array([111,   1,   2,   3,   4])

In [153]:
c

array([0, 1, 2, 3, 4])

# Automatic Reshaping

In [154]:
arr1 = np.arange(40)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [157]:
arr1.shape = 10,4
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [162]:
arr1.shape = 5,2,-1
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]]])

# Stacking or concatenation in an array

In [164]:
arr1 = np.array([['UP', 'MP'],['KA', 'TN']])

arr2 = np.array([['DL', 'RJ'],['KL','AP']])

arr1.shape
arr2.shape

(2, 2)

In [166]:
np.concatenate((arr1,arr2))

array([['UP', 'MP'],
       ['KA', 'TN'],
       ['DL', 'RJ'],
       ['KL', 'AP']], dtype='<U2')

In [167]:
np.concatenate((arr1,arr2), axis = 0)

array([['UP', 'MP'],
       ['KA', 'TN'],
       ['DL', 'RJ'],
       ['KL', 'AP']], dtype='<U2')

In [168]:
np.concatenate((arr1,arr2), axis = 1)

array([['UP', 'MP', 'DL', 'RJ'],
       ['KA', 'TN', 'KL', 'AP']], dtype='<U2')

In [169]:
np.vstack((arr1,arr2))

array([['UP', 'MP'],
       ['KA', 'TN'],
       ['DL', 'RJ'],
       ['KL', 'AP']], dtype='<U2')

In [170]:
np.hstack((arr1,arr2))

array([['UP', 'MP', 'DL', 'RJ'],
       ['KA', 'TN', 'KL', 'AP']], dtype='<U2')